#!/usr/bin/env bash
# Ce script configure les résolutions IP pour localhost et facebook.com

# Ajout des nouvelles entrées dans /etc/hosts
sudo sed -i '/127.0.0.1 localhost/c\127.0.0.2 localhost' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Les modifications ont été effectuées."
